"use client";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Theme from "@/components/Theme";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider store={store}>
        <Theme
          options={{
            key: "mui-theme",
          }}
        >
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </Theme>
      </Provider>
    </html>
  );
}
